function setLanguage(lang) {
    currentLanguage = lang;
    const translations = {
        en: {
            "home": "Home",
            "about": "About",
            "diseases": "Diseases",
            "contact": "Contact",
            "hero-title": "Detect Crop Diseases with AI",
            "hero-subtitle": "Upload an image or use your camera to identify plant diseases instantly",
            "use-webcam": "Use Webcam",
            "upload-image": "Upload Image",
            "detection-title": "Disease Detection",
            "webcam-placeholder": "Webcam feed will appear here",
            "upload-label": "Choose or drag an image",
            "results-placeholder": "Results will appear here",
            "detect-disease": "Detect Disease",
            "results-title": "Detection Results",
            "treatment-title": "Recommended Treatment",
            "medicine-title": "Recommended Medicines",
            "prevention-title": "Prevention Tips",
            "stop-webcam": "Stop Camera",
            "capture-photo": "Capture Photo",
            "clear-image": "Clear Image",
            "footer-about": "About AgroVision",
            "footer-about-text": "AI-powered crop disease detection system helping farmers worldwide.",
            "footer-links": "Quick Links",
            "footer-contact": "Contact Us",
            "footer-copyright": "© 2023 AgroVision. All rights reserved.",
            "chatbot-title": "AgroVision Assistant",
            "chatbot-placeholder": "Type your question..."
        },
        es: {
            "home": "Inicio",
            "about": "Acerca de",
            "diseases": "Enfermedades",
            "contact": "Contacto",
            "hero-title": "Detecta Enfermedades de Cultivos con IA",
            "hero-subtitle": "Sube una imagen o usa tu cámara para identificar enfermedades de plantas al instante",
            "use-webcam": "Usar Cámara",
            "upload-image": "Subir Imagen",
            "detection-title": "Detección de Enfermedades",
            "webcam-placeholder": "La cámara aparecerá aquí",
            "upload-label": "Elige o arrastra una imagen",
            "results-placeholder": "Los resultados aparecerán aquí",
            "detect-disease": "Detectar Enfermedad",
            "results-title": "Resultados de Detección",
            "treatment-title": "Tratamiento Recomendado",
            "medicine-title": "Medicamentos Recomendados",
            "prevention-title": "Consejos de Prevención",
            "stop-webcam": "Detener Cámara",
            "capture-photo": "Capturar Foto",
            "clear-image": "Limpiar Imagen",
            "footer-about": "Acerca de AgroVision",
            "footer-about-text": "Sistema de detección de enfermedades en cultivos potenciado por IA que ayuda a agricultores en todo el mundo.",
            "footer-links": "Enlaces Rápidos",
            "footer-contact": "Contáctenos",
            "footer-copyright": "© 2023 AgroVision. Todos los derechos reservados.",
            "chatbot-title": "Asistente AgroVision",
            "chatbot-placeholder": "Escribe tu pregunta..."
        },
        hi: {
            "home": "होम",
            "about": "हमारे बारे में",
            "diseases": "रोग",
            "contact": "संपर्क करें",
            "hero-title": "AI के साथ फसल रोगों का पता लगाएं",
            "hero-subtitle": "पौधों की बीमारियों को तुरंत पहचानने के लिए एक छवि अपलोड करें या अपने कैमरे का उपयोग करें",
            "use-webcam": "वेबकैम का उपयोग करें",
            "upload-image": "छवि अपलोड करें",
            "detection-title": "रोग पहचान",
            "webcam-placeholder": "वेबकैम फीड यहां दिखाई देगी",
            "upload-label": "एक छवि चुनें या खींचें",
            "results-placeholder": "परिणाम यहां दिखाई देंगे",
            "detect-disease": "रोग का पता लगाएं",
            "results-title": "पहचान परिणाम",
            "treatment-title": "अनुशंसित उपचार",
            "medicine-title": "अनुशंसित दवाएं",
            "prevention-title": "रोकथाम के उपाय",
            "stop-webcam": "कैमरा बंद करें",
            "capture-photo": "फोटो कैप्चर करें",
            "clear-image": "छवि साफ करें",
            "footer-about": "एग्रोविजन के बारे में",
            "footer-about-text": "AI-संचालित फसल रोग पहचान प्रणाली जो दुनिया भर के किसानों की मदद करती है।",
            "footer-links": "त्वरित लिंक",
            "footer-contact": "हमसे संपर्क करें",
            "footer-copyright": "© 2023 एग्रोविजन। सर्वाधिकार सुरक्षित।",
            "chatbot-title": "एग्रोविजन सहायक",
            "chatbot-placeholder": "अपना प्रश्न टाइप करें..."
        },
        np: {
            "home": "गृहपृष्ठ",
            "about": "हाम्रो बारेमा",
            "diseases": "रोगहरू",
            "contact": "सम्पर्क गर्नुहोस्",
            "hero-title": "AI को साथ बालीनाली रोगहरू पत्ता लगाउनुहोस्",
            "hero-subtitle": "एउटा तस्वीर अपलोड गर्नुहोस् वा आफ्नो क्यामेरा प्रयोग गरेर रोगहरू पत्ता लगाउनुहोस्",
            "use-webcam": "वेबक्याम प्रयोग गर्नुहोस्",
            "upload-image": "तस्वीर अपलोड गर्नुहोस्",
            "detection-title": "रोग पत्ता लगाउने",
            "webcam-placeholder": "वेबक्याम यहाँ देखिनेछ",
            "upload-label": "तस्वीर छान्नुहोस् वा तान्नुहोस्",
            "results-placeholder": "नतिजा यहाँ देखिनेछ",
            "detect-disease": "रोग पत्ता लगाउनुहोस्",
            "results-title": "पत्ता लगाउने नतिजा",
            "treatment-title": "सिफारिस गरिएको उपचार",
            "medicine-title": "सिफारिस गरिएका औषधिहरू",
            "prevention-title": "रोकथाम सल्लाहहरू",
            "stop-webcam": "क्यामेरा बन्द गर्नुहोस्",
            "capture-photo": "फोटो क्याप्चर गर्नुहोस्",
            "clear-image": "तस्वीर मेटाउनुहोस्",
            "footer-about": "AgroVision को बारेमा",
            "footer-about-text": "AI-सक्षम बालीनाली रोग पत्ता लगाउने प्रणाली जसले विश्वभरका किसानहरूलाई मद्दत गर्दछ।",
            "footer-links": "छिटो लिङ्कहरू",
            "footer-contact": "हामीलाई सम्पर्क गर्नुहोस्",
            "footer-copyright": "© २०२३ AgroVision. सर्वाधिकार सुरक्षित।",
            "chatbot-title": "AgroVision सहायक",
            "chatbot-placeholder": "आफ्नो प्रश्न टाइप गर्नुहोस्..."
        },
        bh: {
            "home": "घर",
            "about": "हमार बारे में",
            "diseases": "रोग",
            "contact": "संपर्क करीं",
            "hero-title": "AI के सहायता से फसल के बीमारी के पता लगाव",
            "hero-subtitle": "एगो तस्वीर अपलोड करीं या अपना कैमरा के इस्तेमाल करके पौधा के बीमारी के पहचान करीं",
            "use-webcam": "वेबकैम इस्तेमाल करीं",
            "upload-image": "तस्वीर अपलोड करीं",
            "detection-title": "बीमारी के पहचान",
            "webcam-placeholder": "वेबकैम यहाँ देखाई देई",
            "upload-label": "तस्वीर चुनीं या खींचीं",
            "results-placeholder": "नतीजा यहाँ देखाई देई",
            "detect-disease": "बीमारी के पता लगाव",
            "results-title": "पहचान के नतीजा",
            "treatment-title": "सलाह दिहल उपचार",
            "medicine-title": "सलाह दिहल दवाई",
            "prevention-title": "रोकथाम के सलाह",
            "stop-webcam": "कैमरा बंद करीं",
            "capture-photo": "फोटो कैप्चर करीं",
            "clear-image": "तस्वीर साफ करीं",
            "footer-about": "एग्रोविजन के बारे में",
            "footer-about-text": "AI-चालित फसल बीमारी पहचान प्रणाली जवन दुनिया भर के किसान के मदद करेला।",
            "footer-links": "जल्दी लिंक",
            "footer-contact": "हमसे संपर्क करीं",
            "footer-copyright": "© 2023 एग्रोविजन। सब अधिकार सुरक्षित।",
            "chatbot-title": "एग्रोविजन सहायक",
            "chatbot-placeholder": "अपना सवाल टाइप करीं..."
        }
    };